/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 02 21:33:28 GMT 2017
 */

package models;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.List;
import models.Card;
import models.Deck;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Deck_ESTest extends Deck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Deck deck0 = new Deck();
      Deck deck1 = new Deck();
      Deck deck2 = new Deck();
      deck1.cards = deck0.cards;
      deck1.cards = deck2.cards;
      deck1.cards = null;
      // Undeclared exception!
      try { 
        deck1.shuffle();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Deck deck0 = new Deck();
      Random.setNextRandom(Integer.MIN_VALUE);
      // Undeclared exception!
      try { 
        deck0.shuffle();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Deck deck0 = new Deck();
      Deck deck1 = new Deck();
      deck0.cards = deck1.cards;
      deck0.cards = null;
      // Undeclared exception!
      try { 
        deck0.dealFour();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("models.Deck", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Deck deck0 = new Deck();
      ArrayList<Card> arrayList0 = deck0.dealFour();
      deck0.cards = (List<Card>) arrayList0;
      assertEquals(4, arrayList0.size());
      
      ArrayList<Card> arrayList1 = deck0.dealFour();
      ArrayList<Card> arrayList2 = deck0.dealFour();
      assertFalse(arrayList2.equals((Object)arrayList1));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Deck deck0 = new Deck();
      deck0.shuffle();
  }
}
